global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using SmartMealPlanner.Application.Common.Interfaces;                                                                                                          
global using SmartMealPlanner.Domain.Entities;
global using SmartMealPlanner.Domain.Enums;